fragment sectionGeneric on SectionGeneric {
    __typename
    title
    contentCollection {
        items {
            ... on Entry {
                sys { id}
                __typename
            }
            ... on LayoutGrid {
                title
            }
        }
    }
    containerWidth
}
