query layoutGridById($id: String!, $preview: Boolean) {
    layoutGrid(id: $id, preview: $preview) {
        title
        columns
        elementsCollection {
            items {
                __typename

                ... on ElementColumn {
                    elementsCollection {
                        items {
                            __typename
                            title
                            text {
                                json
                            }
                        }
                    }
                }
                ...on ElementText {
                    __typename
                    text {
                        json
                    }
                }
                ...elementImage
                ...elementCard
            }
        }
    }
}
