query pageGenericById($id: String!) {
    pageGeneric(id: $id) {
        sys {
            id
        }
        title
        sectionsCollection {
            items {
                __typename
                ...sectionHero
                ...sectionGeneric
            }
        }
    }
}
