query pageGenericBySlug($slug: String, $preview: Boolean, $locale: String = "en-US") {

    pageGenericCollection(where: { slug: $slug}, preview: $preview, locale: $locale) {
        items {
            sys {
                id
            }
            title
            sectionsCollection {
                items {
                    ...genericEntry
                    ... on SectionGeneric {
                        background
                    }
                }
            }
        }
    }
}
