query queryProjects($preview: Boolean) {
    contentProjectCollection(preview: $preview) {
        items {
            slug
            title
            description {
                json
            }
            creator
        }
    }
}
